format="$time$directory$git_branch$status$character"

[character]
success_symbol="\n[➜](bold green)"
error_symbol="\n[➜](bold red)"


[time]
format="[$time]($style) "
disabled=false

[git_branch]
symbol=""

[directory]
format="in [$path]($style)[$read_only]($read_only_style) "

[package]
disabled=true

[line_break]
disabled=false
